### ISSUE TITLE
Mark all migrations with compatible version (e.g. `Migration[4.2]`)

### ISSUE THREAD

**Issue by cessor** [fgrng/bASSIST#1]
# Description

When installing bASSIST from scratch, I noticed that migrations were failing (Rails 6.1, current Gemfile). 

# Expected behavior

Migrations are applied properly:

```sh
root@758ca9ebff00:/opt/bassist# rails db:migrate
== 20150920104905 CreateExercises: migrating ==================================
-- create_table(:exercises, {:id=>:integer})
   -> 0.0009s
   ...
```

# Actual behavior

Migrations are failing and the rake task is aborted:

```sh
root@73f52a0449d3:/opt/bassist# rake db:migrate
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateExercises < ActiveRecord::Migration[4.2]
```

Full log attached. [error_message.txt](https://github.com/fgrng/bASSIST/files/7853559/error_message.txt)

# Steps to reproduce 

1. Fresh install of branch `csv_import`
2. Added `config/application.yml`
3. Run: 

`$ RAILS_ENV=production rake db:migrate`

# Possible Fix

A possible solution is to tag all original migrations with `[4.2]`. After this change, all migrations are applied. 

```sh
$ sed -i 's/ActiveRecord::Migration/ActiveRecord::Migration[4.2]/g' db/migrate/2015*rb
```

**Comment by fgrng** [comment]
Issue fixed as suggested. Thank you!
