### ISSUE TITLE
Password reset causes NoMethodError in PasswordResetsController#update

### ISSUE THREAD

**Issue by cessor** [fgrng/bASSIST#5]
Resetting your password causes "NoMethodError in PasswordResetsController#update" 

Source of this error appears to be ```app/controllers/password_resets_controller.rb:27``` where `@user.update_attributes` is called, which has been deprecated in 2018: 

```
elsif @user.update_attributes(params[:user].permit(:password, :password_confirmation))
```

The following issues describe the deprecation procedure and a fix is suggested: 

 - https://github.com/rails/rails/pull/8705
 - https://github.com/rails/rails/pull/31998

Apparently, the method moved to [ActiveRecord::Persistence.update](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update). 

Is it possible for you to fix & test this?

**Comment by cessor** [comment]
I applied a quickfix in my own Docker-deployment to mitigate the issue, by including:
```
RUN sed -i s/@user.update_attributes/@user.update/g /opt/bassist/app/controllers/password_resets_controller.rb
```

Can you please confirm that `user.update` is a viable fix for this issue? Ideally, I would rather this was fixed up stream so that our local changes don't deviate too much from origin.

**Comment by fgrng** [comment]
Fixed as suggested, thank you. See #7
