### ISSUE TITLE
CSV-Import causes file not found in second step of upload.

### ISSUE THREAD

**Issue by cessor** [fgrng/bASSIST#6]
## Description 

During testing of the updated assist deployment, we encountered the following error:

![BetaAssist](https://user-images.githubusercontent.com/117452/153463030-09c31fa3-3e1a-4182-af7d-1be25c95131b.PNG)

This error occurs when an assistant uploads a CSV file. After this error occurred, a course is created, however, no data has been added (no subjects, no students, no submissions). 

## Expected Behavior

The upload causes no error and the pseudo-course and student submissions are created. 

## Steps to Reproduce

1. Log in as an assistant or any other role who can perform CSV-imports
2. Goto the CSV upload form by clicking on the button on the dashboard
3. User is redirected to `lectures/import_new` and a form to create a pseudo-course is shown
4. Provide a title and lecture data, select a CSV-File to upload
5. Submit the form. A POST request to `/lectures/import_conf` is performed
6. The following page correctly shows a form which allows the user to configure field mappings (StatementABC, User-ID, etc.)
7. Submit. Accept notification that imports might take a while
8. A POST request to `/lectures/import_create` is performed. 
9. Application crashes, shows page as shown in screenshot. 

Please find attached a logfile of the above steps: 

[github-issue-6.txt](https://github.com/fgrng/bASSIST/files/8043195/github-issue-6.txt)

**Comment by fgrng** [comment]
Fixed by #8. 

Uploaded CSV file was deleted between data processing steps due to ActionDispatch::Http::UploadedFile being a Tempfile. I am not sure why this issue was not present in older versions. Issue is now prevented by making a permanent copy after upload. Copy is deleted at the data import step.
